// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpmmdcfrjtgadikqgfqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbW1kY2ZyanRnYWRpa3FnZnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTY3NDYsImV4cCI6MjA3MDY3Mjc0Nn0.b33FOO4aOMVUY-aTk4ieqjddPs6cq7wOqm_Le8v7MSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});